kind: pipeline
type: kubernetes
name: build

platform:
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: harbor.hnatekmar.xyz/library/mirage
      autotag: true
      tags:
        - base
      settings:
        username: drone
        password: 
          from_secret: registry_login
