kind: pipeline
type: kubernetes
name: build

platform:
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: harbor.hnatekmar.xyz
      repo: harbor.hnatekmar.xyz/library/mirage
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
