kind: pipeline
type: kubernetes
name: build

platform:
  arch: amd64

steps:
  - name: docker
    image: docker
    secrets: [registry_username,registry_password]
    commands:
      - docker login --username=$REGISTRY_USERNAME --password=$REGISTRY_PASSWORD harbor.hnatekmar.xyz
      - docker build -t harbor.hnatekmar.xyz/public/mirage:${DRONE_COMMIT} .
      - docker push harbor.hnatekmar.xyz/public/mirage:${DRONE_COMMIT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
