kind: pipeline
name: default

steps:
  - name: test
    image: ubuntu:20.04
    commands:
      - apt-get update && apt-get install -y gcc g++ libboost-all-dev cmake
      - cd project
      - mkdir build
      - cd build
      - cmake ..
      - make -j $(nproc)