kind: pipeline
type: kubernetes
name: test-on-amd64

platform:
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.hnatekmar.xyz/tpj
      autotag: true
      tags:
        - base