kind: pipeline
type: kubernetes
name: build

platform:
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: harbor.hnatekmar.xyz/library/mirage
      autotag: true
      tags:
        - base
      username: drone
      password:
        from_secret: registry_password
      custom_dns: [172.16.100.1]
