kind: pipeline
type: kubernetes
name: build

platform:
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: public-registry.hnatekmar.xyz/mirage
      autotag: true
      tags:
        - base
