kind: pipeline
type: kubernetes
name: build

platform:
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    environment:
      TOKEN:
        from_secret: registry_token
    settings:
      repo: harbor.hnatekmar.xyz/library/mirage
      autotag: true
      tags:
        - base
      build_args_from_env:
        - TOKEN
