kind: pipeline
type: kubernetes
name: build

platform:
  arch: amd64

steps:
  - name: docker
    image: docker:dind
    secrets: [registry_username,registry_password]
    commands:
      - echo $REGISTRY_PASSWORD | docker login --username=$REGISTRY_USERNAME --password-stdin harbor.hnatekmar.xyz
      - docker build -t harbor.hnatekmar.xyz/public/mirage:${DRONE_COMMIT} .
      - docker push harbor.hnatekmar.xyz/public/mirage:${DRONE_COMMIT}
    volumes:
      - name: dockersock
        path: /var/run
