kind: pipeline
type: kubernetes
name: build

platform:
  arch: amd64

steps:
  - name: docker
    image: docker:dind
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
    commands:
      - echo $PASSWORD | docker login --username=$USERNAME --password-stdin harbor.hnatekmar.xyz
      - docker build -t harbor.hnatekmar.xyz/public/mirage:${DRONE_COMMIT} .
      - docker push harbor.hnatekmar.xyz/public/mirage:${DRONE_COMMIT}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
