language: cpp

sudo: required

compiler:
        - g++
        - clang

os:
        - linux
        - osx

addons:
        apt:
                packages:
                        - libboost-all-dev

script:
        - cd project/
        - cmake CMakeLists.txt
        - make
