language: cpp
sudo: required
compiler:
        - g++
        - clang

os:
        - linux
        - osx

addons:
        apt:
                sources:
                        - boost-latest
                packages:
                        - libboost1.61-dev
                        - cmake

script:
        - cd project/
        - cmake CMakeLists.txt
        - make
