language: cpp
sudo: required
compiler:
        - gcc
os:
        - linux
        - osx

addons:
        apt:
                - libboost1.61-dev

script:
        - cd project/
        - cmake CMakeLists.txt
        - make
