projekt:
	./grammar.py gramatiky/identifikator.json > identifikator.tex
	./grammar.py gramatiky/cisla.json > cisla.tex
	./grammar.py gramatiky/slova.json > slova.tex
	./automat.py gramatiky/*.json > automat.tex
